version: '3.3'

services:
  currency:
    container_name: currency
    build: .
    image: currency

    ports:
      - "9003:9003"

    restart: on-failure
    environment:
      - spring_rabbitmq_host=rabbit
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest

    networks:
      - default
      - rabbitmq_default

networks:
  default:
    internal: true
  rabbitmq_default:
    external: true